/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Governance } from "./Governance";
export * as factories from "./factories";
export { Governance__factory } from "./factories/Governance__factory";
